package controller;

public enum Commands {	
    ADD,
    DELETE,
    SPANISH,
    ENGLISH,
    EDIT,
    SEARCH,
    SEE_LIST,
    SEE_AVERAGE,
    EXPORT,
    GET_OUT,
    CLOSE_ADD_DIALOG,
    CLOSE_DIALOG_ADD_CANCEL,
    CLOSE_DELETE_DIALOG,
    CLOSE_DIALOG_DELETE_CANCEL,
    CLOSE_EDIT_DIALOG,
    CLOSE_DIALOG_EDIT_CANCEL,
    CLOSE_EDIT_RUNNER_DIALOG,
    CLOSE_DIALOG_EDIT_RUNNER_CANCEL,
    ENTER_REPORT;
}
