package views;

import java.awt.Color;

public class Constants{
	
	public static final Color GRAY = Color.decode("#888888");
	public static final Color GRAY_LIGHT = Color.decode("#E8E8E8");
	public static final Color GRAT_DARK = Color.decode("#4A4848");
	public static final Color GRAY_BLUE = Color.decode("#ACACAC");
	public static final Color GRAY_RED = Color.decode("#969696");
	public static final Color RED = Color.decode("#FF0000");
	public static final Color CIAN = Color.decode("#00F0FF");
	public static final Color ORANGE = Color.decode("#FFAE00");
	public static final String MESSAGE_ARRAY_INDEX = "Opcion no valida";
	public static final String MESSAGE_NUMBER_FORMAT = "El ID no es valido";
	public static final String MESSAGE_CREATE_POND = "El cultivo ha sido añadido";
	public static final String MESSAGE_EMPTY_FIELDS = "";
	public static final String END_PROGRAM = "Programa finalizado";
	public static final String MESSAGE_IVALID_OPTION = "Opcion invalida";
	public static final String MESSAGE_CORRECT_DELETE = "Cultivo eliminado";
	public static final String MESSAGE_CONFIRMATION = "¿Estás seguro que deseas salir del programa?";
	public static final String MESSAGE_CONFIRMATION_DELETE = "¿Estás seguro que deseas eliminar el cultivo?";
	public static final String BACKGROUND_COLOR_DECODE = "#ececec";
	public static final String ROUTE_DATA = "Resources/registros.txt";
	public static final String EMPTY = " ";
	public static final String LIST = "Update_List";
	public static final String EXIT = "Exit";
	public static final String ERROR = "Error: ";
	public static final String SPANISH = "Spanish_LG";
	public static final String ENGLISH = "English_LG";
	public static final String MESSAGE_NOT_FOUND = "Empty_Fields"; 
	public static final String MESSAGE_INPUT_ERROR = "Este input no quiere funcionar"; 
	public static final String IP ="172.16.0.73";
	public static final String WITH_PROXY = "Con proxy";
	public static final String WITHOUT_PROXY = "Sin proxy";
	public static final String MUNICIPALITY_KEY= "municipio";
	public static final String SPECIE_KEY= "especie";
	public static final String YEAR= "Year";
	public static final String YEAT_KEY= "a_o";
	public static final String SEEDED_ANIMALS_KEY= "animales_sembrados";
	public static final String HARVESTED_ANIMALS_KEY= "animales_cosechados";
	public static final String WEIGHT_ANIMALS_KEY= "peso_promedio_por_animal_al_cosechar_g";
	public static final String PRODUCTION_KEY= "produccion_estimada_kg";
	public static final String PRICE_KEY= "precio_al_productor_kg";
	public static final String TITLE_D_ADD= "Ingrese los datos del cultivo de peces";
	public static final String FONT_RUBIK = "Rubik";
	public static final String ACCEPT = "Accept";
	public static final String CANCEL = "Cancel"; 
	public static final String LOGO_PATH = "Resources/logo.png"; 
	public static final String ADD_PATH = "Resources/AddPond.png"; 
	public static final String DELETE_PATH = "Resources/DeletePond.png"; 
	public static final String LIST_PATH = "Resources/seelist.png"; 
	public static final String EXIT_PATH = "Resources/getout.png"; 
	public static final String USA_PATH = "Resources/BEU.png"; 
	public static final String SPAIN_PATH = "Resources/Bsp.png"; 
	public static final String TITLE = "Title"; 
	public static final String SELECT_SPECIE = "Select_Specie"; 
	public static final String SELECT_MUNICIPALITY = "Select_Municipality"; 
	public static final String IN_SEEDED_ANIMALS = "In_Seeded_Animals"; 
	public static final String IN_HARVESTED_ANIMALS = "In_Harvested_Animals"; 
	public static final String IN_WEIGHT_ANIMALS = "In_Average_Weight"; 
	public static final String IN_PRODUCTION_ANIMALS = "In_Estimed_Production"; 
	public static final String IN_PRICE_ANIMALS = "In_Comsumer_Price"; 
	public static final String IN_ID = "In_Id"; 
	public static final String IN_YEAR = "In_Year"; 
	public static final String ADD_POND = "Add_Element"; 
	public static final String DELETE_POND = "Delete_Elment"; 
	public static final String ID = "Id"; 
	public static final String MUNICIPALITY= "Municipality"; 
	public static final String SPECIE = "Specie"; 
	public static final String SEEDED_ANIMALS = "Seeded_Animals"; 
	public static final String HARVESTED_ANIMALS = "Harvested_Animals"; 
	public static final String WEIGHT_ANIMAL = "Average_Weight"; 
	public static final String PRODUCTION = "Estimated_Production"; 
	public static final String PRICE_ANIMAL = "Price";
	public static final String VERIFY = "Confirmar";
}